// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arzutywyhhwojhecyseg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyenV0eXd5aGh3b2poZWN5c2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTY5ODAsImV4cCI6MjA3MjYzMjk4MH0.3lAiXDxrUvzt3_KcEFtsVvy7d9yEDo_c_wolsFUwJeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});